In [101]:
import numpy as np

**Valid Sudoku**

In [102]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [103]:
a= s.sum(axis=1)


for i in a:
  if i !=45:
    print("Sudoku is not correct")
    break
  else:
    print("Sudoku is correct ")
    break




Sudoku is correct 


In [104]:
b= s.sum(axis=0)

for i in b:
  if i != 45:
   print("Sudoku is not correct")

  else:
    print("Sudoku is correct ")
    break


Sudoku is correct 


In [105]:
a = s[0:3,0:3]
a.sum()

np.int64(45)

In [106]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3,j:j+3]
    print(n.sum())


45
45
45
45
45
45
45
45
45


In [107]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [108]:
data.shape

(5, 3)

find minimum age

In [109]:
a = data[0:5,0]
a.min()

np.int64(17)

avg of age

In [110]:
np.mean(data[0:5,0])

np.float64(18.4)

In [111]:
data[:5,1]

array([85, 92, 76, 65, 90])

In [112]:
b= data[:5,2]
b.max()

np.int64(95)

In [113]:
c = data[:5,1]

for i in c:
  if i>= 90:
    print(i)

92
90


In [114]:
data[:,1] += 5

data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [115]:
len(data[data[:5,0] < 19])

3

In [116]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [117]:
data[(data[:,1]>=80)& (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [118]:
data[:,2][data[:,2]<75] =0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])