In [2]:
import numpy as np

In [3]:
# make array


a = np.array([1,2,3,4,5])

a

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4,5,"hello"]
# array only store one datatype not multiples data types

np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [5]:
# 2d array

b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
""" make a array in this 1= start point and 11 = end poin
 always take end poin n+1 """

a = np.arange(1,11)

b = 5 * a

b




array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.ones((6,6))
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
""" linespace is give equal space in this queation 1 to 5 number we take and
3 number print  """

d = np.linspace(1,5,3)


d

array([1., 3., 5.])

In [10]:
import random

In [11]:
np.random.rand(1)

array([0.49363627])

In [12]:
""" this use for genrate 10 random number between 10 to 20
and print 10 random number"""

np.random.randint(10,20,10)

array([12, 17, 12, 19, 15, 17, 14, 17, 19, 16])

In [13]:
e =np.array([[10,20,30,4],[5,60,7,8]])
e


array([[10, 20, 30,  4],
       [ 5, 60,  7,  8]])

In [14]:
""" using .shape  we find how many rows adn columns their    """

e.shape

(2, 4)

In [15]:
"""using .size we find total elementin array     """

e.size

8

In [16]:
""".dtype we find datatype     """


e.dtype

dtype('int64')

In [17]:
a = e.min() #.min for find minimum value in array
b = e.max() #.max for find maximum value in array
c= e.sum()  #.sum for find sum of enire array
print(a)
print(b)
print(c)

4
60
144


In [18]:
a =np.sum(e,axis=1) # axis=1 use for sum of rows in this 64 for row 1 and 80 is row 2
b =np.sum(e,axis=0) # axis =0 use for sum columns
print(a)
print(b)

[64 80]
[15 80 37 12]


In [19]:
np.min(e,axis=1)

array([4, 5])

In [20]:
np.max(e,axis=1)

array([30, 60])

In [21]:
e.std()

np.float64(17.89553016817328)

In [22]:
e.argmax() # .argmax() use for find maximum value index

np.int64(5)

In [23]:
e.argmin()# .argmin() use for find minimum value index

np.int64(3)

In [24]:
a= np.arange(1,31)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [25]:
a = a.reshape(6,5) # converte 1d array in 2d/matrix array

In [26]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a[19]

np.int64(20)

In [29]:
b = a[1:5]

In [30]:
arr = np.arange(1,31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr[5,0]

np.int64(26)

In [32]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [33]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool= arr %2 == 0
bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr = arr[bool]
arr

array([12, 14, 16, 18, 20])

In [36]:
a = np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
print(a)
print(b)


[1 2 3 4 5]
[ 6  7  8  9 10]


**Arithmetic Operations **

In [37]:
#

print(a+b)
print(b-a)
print(a*b)
print(a/b)
print(a//b)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]


 **Broadcasting **

In [38]:
l = [10,20,30,40]
arr  = np.array(l)

In [39]:
arr+10

array([20, 30, 40, 50])

In [40]:
c= np.arange(1,26).reshape(5,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
c +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [42]:
c*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [43]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
d = a[0:5]
d*5


array([ 5, 10, 15, 20, 25])

In [50]:
m1 = np.arange(1,5).reshape(2,2)
m2 = np.arange(5,9).reshape(2,2)


In [52]:
m1

array([[1, 2],
       [3, 4]])

In [53]:
m2

array([[5, 6],
       [7, 8]])

matrix multiplication

In [55]:
np.dot(m1,m2)
m1@m2

array([[19, 22],
       [43, 50]])

transpose

In [56]:
m1.T

array([[1, 3],
       [2, 4]])

**stack of array**

In [57]:
a = np.array([1,2,3,4])

In [58]:
b= np.array([5,6,7,8])

In [59]:
np.vstack((a,b)) #array stack in vertical

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
np.hstack((a,b)) # array stack in horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.column_stack((a,b)) # make column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting  Array**

In [91]:
c = np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.split(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [93]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [94]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]