In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = [1,2,3,4,5,"hello"]


np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a = np.arange(1,11)

b = 5 * a

b




array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.ones((6,6))
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
d = np.linspace(1,5,3)
d

array([1., 3., 5.])

In [ ]:
import random

In [ ]:
np.random.rand(1)

array([0.42548448])

In [ ]:
np.random.randint(10,20,10)

array([19, 14, 12, 16, 10, 17, 15, 10, 14, 16])

In [ ]:
e =np.array([[10,20,30,4],[5,60,7,8]])
e


array([[10, 20, 30,  4],
       [ 5, 60,  7,  8]])

In [ ]:
e.shape

(2, 4)

In [ ]:
e.size

8

In [ ]:
e.dtype

dtype('int64')

In [ ]:
a = e.min()
b = e.max()
c= e.sum()
print(a)
print(b)
print(c)

4
60
144


In [ ]:
np.sum(e,axis=1)

array([64, 80])

In [ ]:
np.min(e,axis=1)

array([4, 5])

In [ ]:
np.max(e,axis=1)

array([30, 60])

In [ ]:
e.std()

np.float64(17.89553016817328)

In [ ]:
e.argmax()

np.int64(5)

In [ ]:
e.argmin()

np.int64(3)

In [ ]:
a= np.arange(1,31)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a = a.reshape(6,5)

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[19]

np.int64(20)

In [ ]:
b = a[1:5]

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5,0]

np.int64(26)

In [ ]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])