**Student Marks Analysis (Data Processing)**

In [29]:
import numpy as np

marks = np.array([
    [85, 78, 92, 88],
    [76, 81, 79, 85],
    [90, 92, 94, 91],
    [65, 70, 72, 68],
    [88, 84, 91, 87]
])
marks

array([[85, 78, 92, 88],
       [76, 81, 79, 85],
       [90, 92, 94, 91],
       [65, 70, 72, 68],
       [88, 84, 91, 87]])

In [30]:
# Find average marks per student
averagemarks = marks.mean(axis=1)
averagemarks

array([85.75, 80.25, 91.75, 68.75, 87.5 ])

In [31]:
# Find highest scorer

highestscorer = marks.max(axis=1)
highestscorer

array([92, 85, 94, 72, 91])

In [32]:
# Find subject-wise average
averagemarks = marks.mean(axis=0)
averagemarks


array([80.8, 81. , 85.6, 83.8])

In [33]:
# Add 5 bonus marks to all students
bonusmarks = 5
marks += bonusmarks
marks

array([[90, 83, 97, 93],
       [81, 86, 84, 90],
       [95, 97, 99, 96],
       [70, 75, 77, 73],
       [93, 89, 96, 92]])

In [34]:
# Find students scoring >85 overall

a = marks[:4,3]
for i in a:
  if i > 85:
    print(i)

93
90
96


**E-commerce Sales Data (Business Analytics)**

In [35]:
sales = np.array([200, 220, 250, 300, 280, 260, 310])

In [36]:
# Calculate total revenue

total=sales.sum()
total

np.int64(1820)

In [37]:
# Find day with maximum sales

maxsales=sales.max()
maxsales

np.int64(310)

In [38]:
# Compute moving average (window=3)
window = 3

c = np.cumsum(sales, dtype=float)

moving_avg = (c[window:] - c[:-window]) / window

moving_avg


array([256.66666667, 276.66666667, 280.        , 283.33333333])

In [39]:
# Normalize sales data (0–1 scale)
normalized_sales = (sales - sales.min()) / (sales.max() - sales.min())
normalized_sales

array([0.        , 0.18181818, 0.45454545, 0.90909091, 0.72727273,
       0.54545455, 1.        ])

In [40]:
# Find percentage increase each day
percentage= sales[:6]
p =0
for i in percentage:
  a =((i-p)/p)*100
  p = i
  print(a)



inf
10.0
13.636363636363635
20.0
-6.666666666666667
-7.142857142857142


/tmp/ipykernel_25126/133415041.py:5: RuntimeWarning: divide by zero encountered in scalar divide
  a =((i-p)/p)*100
